/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PaymentMode = IDL.Variant({
  'upi' : IDL.Null,
  'card' : IDL.Null,
  'cash' : IDL.Null,
});
export const BanquetBill = IDL.Record({
  'id' : IDL.Text,
  'contactName' : IDL.Text,
  'guestCount' : IDL.Nat,
  'createdAt' : IDL.Int,
  'gstPercent' : IDL.Float64,
  'hallName' : IDL.Text,
  'totalAmount' : IDL.Float64,
  'paymentMode' : PaymentMode,
  'extraCharges' : IDL.Float64,
  'perPlateRate' : IDL.Float64,
  'eventName' : IDL.Text,
  'contactPhone' : IDL.Text,
});
export const OrderItem = IDL.Record({
  'qty' : IDL.Nat,
  'name' : IDL.Text,
  'notes' : IDL.Text,
  'price' : IDL.Float64,
  'menuItemId' : IDL.Text,
});
export const RestaurantBill = IDL.Record({
  'id' : IDL.Text,
  'customerName' : IDL.Opt(IDL.Text),
  'createdAt' : IDL.Int,
  'tableId' : IDL.Text,
  'gstAmount' : IDL.Float64,
  'orderId' : IDL.Text,
  'totalAmount' : IDL.Float64,
  'discount' : IDL.Float64,
  'paymentMode' : PaymentMode,
  'items' : IDL.Vec(OrderItem),
  'subtotal' : IDL.Float64,
});
export const RestaurantCustomer = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'loyaltyPoints' : IDL.Nat,
  'totalSpend' : IDL.Float64,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const RestaurantDue = IDL.Record({
  'id' : IDL.Text,
  'customerName' : IDL.Text,
  'dueDate' : IDL.Int,
  'description' : IDL.Text,
  'isPaid' : IDL.Bool,
  'customerId' : IDL.Text,
  'amount' : IDL.Float64,
});
export const RestaurantExpense = IDL.Record({
  'id' : IDL.Text,
  'date' : IDL.Int,
  'description' : IDL.Text,
  'paymentMode' : PaymentMode,
  'category' : IDL.Text,
  'amount' : IDL.Float64,
});
export const GuestCheckInStatus = IDL.Variant({
  'checkedIn' : IDL.Null,
  'checkedOut' : IDL.Null,
});
export const GuestCheckIn = IDL.Record({
  'id' : IDL.Text,
  'status' : GuestCheckInStatus,
  'createdAt' : IDL.Int,
  'checkInDate' : IDL.Text,
  'guestName' : IDL.Text,
  'roomNumber' : IDL.Text,
  'children' : IDL.Nat,
  'idNumber' : IDL.Text,
  'totalAmount' : IDL.Float64,
  'notes' : IDL.Text,
  'advancePaid' : IDL.Float64,
  'adults' : IDL.Nat,
  'expectedCheckOut' : IDL.Text,
  'phone' : IDL.Text,
  'idType' : IDL.Text,
  'actualCheckOut' : IDL.Text,
});
export const RoomFoodOrder = IDL.Record({
  'id' : IDL.Text,
  'roomNumber' : IDL.Text,
  'guestName' : IDL.Text,
  'items' : IDL.Vec(OrderItem),
  'totalAmount' : IDL.Float64,
  'gstAmount' : IDL.Float64,
  'paymentMode' : PaymentMode,
  'notes' : IDL.Text,
  'createdAt' : IDL.Int,
  'isPaid' : IDL.Bool,
});
export const RoomInvoice = IDL.Record({
  'id' : IDL.Text,
  'guestCheckInId' : IDL.Text,
  'guestName' : IDL.Text,
  'roomNumber' : IDL.Text,
  'roomType' : IDL.Text,
  'checkInDate' : IDL.Text,
  'checkOutDate' : IDL.Text,
  'nights' : IDL.Nat,
  'roomRate' : IDL.Float64,
  'roomCharges' : IDL.Float64,
  'foodCharges' : IDL.Float64,
  'otherCharges' : IDL.Float64,
  'discount' : IDL.Float64,
  'gstPercent' : IDL.Float64,
  'gstAmount' : IDL.Float64,
  'totalAmount' : IDL.Float64,
  'advancePaid' : IDL.Float64,
  'balanceDue' : IDL.Float64,
  'paymentMode' : PaymentMode,
  'notes' : IDL.Text,
  'createdAt' : IDL.Int,
});
export const RestaurantInventory = IDL.Record({
  'id' : IDL.Text,
  'costPerUnit' : IDL.Float64,
  'stockQty' : IDL.Float64,
  'name' : IDL.Text,
  'unit' : IDL.Text,
  'reorderLevel' : IDL.Float64,
});
export const MenuCategory = IDL.Record({
  'id' : IDL.Text,
  'sortOrder' : IDL.Nat,
  'name' : IDL.Text,
});
export const MenuItem = IDL.Record({
  'id' : IDL.Text,
  'categoryId' : IDL.Text,
  'name' : IDL.Text,
  'gstPercent' : IDL.Float64,
  'isAvailable' : IDL.Bool,
  'description' : IDL.Text,
  'isVeg' : IDL.Bool,
  'price' : IDL.Float64,
});
export const OrderStatus = IDL.Variant({
  'pending' : IDL.Null,
  'served' : IDL.Null,
  'cooking' : IDL.Null,
  'billed' : IDL.Null,
});
export const RestaurantOrder = IDL.Record({
  'id' : IDL.Text,
  'customerName' : IDL.Opt(IDL.Text),
  'status' : OrderStatus,
  'createdAt' : IDL.Int,
  'tableId' : IDL.Text,
  'gstAmount' : IDL.Float64,
  'totalAmount' : IDL.Float64,
  'items' : IDL.Vec(OrderItem),
});
export const RestaurantReceipt = IDL.Record({
  'id' : IDL.Text,
  'source' : IDL.Text,
  'date' : IDL.Int,
  'note' : IDL.Text,
  'paymentMode' : PaymentMode,
  'amount' : IDL.Float64,
});
export const Type = IDL.Variant({
  'contact' : IDL.Null,
  'banquet' : IDL.Null,
  'booking' : IDL.Null,
});
export const ContactInquiry = IDL.Record({
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
});
export const BanquetInquiry = IDL.Record({
  'guestCount' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
  'eventDate' : IDL.Text,
  'eventType' : IDL.Text,
});
export const BookingInquiry = IDL.Record({
  'checkIn' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'checkOut' : IDL.Text,
  'phone' : IDL.Text,
  'guests' : IDL.Nat,
  'roomType' : IDL.Text,
});
export const InquiryDetails = IDL.Variant({
  'contact' : ContactInquiry,
  'banquet' : BanquetInquiry,
  'booking' : BookingInquiry,
});
export const Inquiry = IDL.Record({
  'id' : IDL.Nat,
  'inquiryType' : Type,
  'timestamp' : IDL.Int,
  'details' : InquiryDetails,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const TableStatus = IDL.Variant({
  'occupied' : IDL.Null,
  'free' : IDL.Null,
  'reserved' : IDL.Null,
});
export const RestaurantTable = IDL.Record({
  'id' : IDL.Text,
  'status' : TableStatus,
  'seats' : IDL.Nat,
  'currentOrderId' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBanquetBill' : IDL.Func([BanquetBill], [], []),
  'createBill' : IDL.Func([RestaurantBill], [], []),
  'createCustomer' : IDL.Func([RestaurantCustomer], [], []),
  'createDue' : IDL.Func([RestaurantDue], [], []),
  'createExpense' : IDL.Func([RestaurantExpense], [], []),
  'createGuestCheckIn' : IDL.Func([GuestCheckIn], [], []),
  'createInventoryItem' : IDL.Func([RestaurantInventory], [], []),
  'createMenuCategory' : IDL.Func([MenuCategory], [], []),
  'createMenuItem' : IDL.Func([MenuItem], [], []),
  'createOrder' : IDL.Func([RestaurantOrder], [], []),
  'createReceipt' : IDL.Func([RestaurantReceipt], [], []),
  'createRoomFoodOrder' : IDL.Func([RoomFoodOrder], [], []),
  'createRoomInvoice' : IDL.Func([RoomInvoice], [], []),
  'deleteBanquetBill' : IDL.Func([IDL.Text], [], []),
  'deleteBill' : IDL.Func([IDL.Text], [], []),
  'deleteCustomer' : IDL.Func([IDL.Text], [], []),
  'deleteDue' : IDL.Func([IDL.Text], [], []),
  'deleteExpense' : IDL.Func([IDL.Text], [], []),
  'deleteGuestCheckIn' : IDL.Func([IDL.Text], [], []),
  'deleteInventoryItem' : IDL.Func([IDL.Text], [], []),
  'deleteMenuCategory' : IDL.Func([IDL.Text], [], []),
  'deleteMenuItem' : IDL.Func([IDL.Text], [], []),
  'deleteOrder' : IDL.Func([IDL.Text], [], []),
  'deleteReceipt' : IDL.Func([IDL.Text], [], []),
  'deleteRoomFoodOrder' : IDL.Func([IDL.Text], [], []),
  'deleteTable' : IDL.Func([IDL.Text], [], []),
  'getAllGuestCheckIns' : IDL.Func([], [IDL.Vec(GuestCheckIn)], ['query']),
  'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getAllRoomFoodOrders' : IDL.Func([], [IDL.Vec(RoomFoodOrder)], ['query']),
  'getAllRoomInvoices' : IDL.Func([], [IDL.Vec(RoomInvoice)], ['query']),
  'getBanquetBill' : IDL.Func([IDL.Text], [IDL.Opt(BanquetBill)], ['query']),
  'getBanquetBills' : IDL.Func([], [IDL.Vec(BanquetBill)], ['query']),
  'getBill' : IDL.Func([IDL.Text], [IDL.Opt(RestaurantBill)], ['query']),
  'getBills' : IDL.Func([], [IDL.Vec(RestaurantBill)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomer' : IDL.Func([IDL.Text], [IDL.Opt(RestaurantCustomer)], ['query']),
  'getCustomers' : IDL.Func([], [IDL.Vec(RestaurantCustomer)], ['query']),
  'getDue' : IDL.Func([IDL.Text], [IDL.Opt(RestaurantDue)], ['query']),
  'getDues' : IDL.Func([], [IDL.Vec(RestaurantDue)], ['query']),
  'getExpense' : IDL.Func([IDL.Text], [IDL.Opt(RestaurantExpense)], ['query']),
  'getExpenses' : IDL.Func([], [IDL.Vec(RestaurantExpense)], ['query']),
  'getGuestCheckIn' : IDL.Func([IDL.Text], [IDL.Opt(GuestCheckIn)], ['query']),
  'getInventoryItem' : IDL.Func([IDL.Text], [IDL.Opt(RestaurantInventory)], ['query']),
  'getInventoryItems' : IDL.Func([], [IDL.Vec(RestaurantInventory)], ['query']),
  'getMenuCategories' : IDL.Func([], [IDL.Vec(MenuCategory)], ['query']),
  'getMenuCategory' : IDL.Func([IDL.Text], [IDL.Opt(MenuCategory)], ['query']),
  'getMenuItem' : IDL.Func([IDL.Text], [IDL.Opt(MenuItem)], ['query']),
  'getMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'getOrder' : IDL.Func([IDL.Text], [IDL.Opt(RestaurantOrder)], ['query']),
  'getOrders' : IDL.Func([], [IDL.Vec(RestaurantOrder)], ['query']),
  'getReceipt' : IDL.Func([IDL.Text], [IDL.Opt(RestaurantReceipt)], ['query']),
  'getReceipts' : IDL.Func([], [IDL.Vec(RestaurantReceipt)], ['query']),
  'getRoomFoodOrder' : IDL.Func([IDL.Text], [IDL.Opt(RoomFoodOrder)], ['query']),
  'getRoomInvoice' : IDL.Func([IDL.Text], [IDL.Opt(RoomInvoice)], ['query']),
  'getTable' : IDL.Func([IDL.Text], [IDL.Opt(RestaurantTable)], ['query']),
  'getTables' : IDL.Func([], [IDL.Vec(RestaurantTable)], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(UserProfile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitBanquet' : IDL.Func([BanquetInquiry], [IDL.Nat], []),
  'submitBooking' : IDL.Func([BookingInquiry], [IDL.Nat], []),
  'submitContact' : IDL.Func([ContactInquiry], [IDL.Nat], []),
  'updateBanquetBill' : IDL.Func([BanquetBill], [], []),
  'updateBill' : IDL.Func([RestaurantBill], [], []),
  'updateCustomer' : IDL.Func([RestaurantCustomer], [], []),
  'updateDue' : IDL.Func([RestaurantDue], [], []),
  'updateExpense' : IDL.Func([RestaurantExpense], [], []),
  'updateGuestCheckIn' : IDL.Func([GuestCheckIn], [], []),
  'updateInventoryItem' : IDL.Func([RestaurantInventory], [], []),
  'updateMenuCategory' : IDL.Func([MenuCategory], [], []),
  'updateMenuItem' : IDL.Func([MenuItem], [], []),
  'updateOrder' : IDL.Func([RestaurantOrder], [], []),
  'updateReceipt' : IDL.Func([RestaurantReceipt], [], []),
  'updateRoomFoodOrder' : IDL.Func([RoomFoodOrder], [], []),
  'updateRoomInvoice' : IDL.Func([RoomInvoice], [], []),
  'updateTable' : IDL.Func([RestaurantTable], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PaymentMode = IDL.Variant({
    'upi' : IDL.Null,
    'card' : IDL.Null,
    'cash' : IDL.Null,
  });
  const BanquetBill = IDL.Record({
    'id' : IDL.Text,
    'contactName' : IDL.Text,
    'guestCount' : IDL.Nat,
    'createdAt' : IDL.Int,
    'gstPercent' : IDL.Float64,
    'hallName' : IDL.Text,
    'totalAmount' : IDL.Float64,
    'paymentMode' : PaymentMode,
    'extraCharges' : IDL.Float64,
    'perPlateRate' : IDL.Float64,
    'eventName' : IDL.Text,
    'contactPhone' : IDL.Text,
  });
  const OrderItem = IDL.Record({
    'qty' : IDL.Nat,
    'name' : IDL.Text,
    'notes' : IDL.Text,
    'price' : IDL.Float64,
    'menuItemId' : IDL.Text,
  });
  const RestaurantBill = IDL.Record({
    'id' : IDL.Text,
    'customerName' : IDL.Opt(IDL.Text),
    'createdAt' : IDL.Int,
    'tableId' : IDL.Text,
    'gstAmount' : IDL.Float64,
    'orderId' : IDL.Text,
    'totalAmount' : IDL.Float64,
    'discount' : IDL.Float64,
    'paymentMode' : PaymentMode,
    'items' : IDL.Vec(OrderItem),
    'subtotal' : IDL.Float64,
  });
  const RestaurantCustomer = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'loyaltyPoints' : IDL.Nat,
    'totalSpend' : IDL.Float64,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const RestaurantDue = IDL.Record({
    'id' : IDL.Text,
    'customerName' : IDL.Text,
    'dueDate' : IDL.Int,
    'description' : IDL.Text,
    'isPaid' : IDL.Bool,
    'customerId' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const RestaurantExpense = IDL.Record({
    'id' : IDL.Text,
    'date' : IDL.Int,
    'description' : IDL.Text,
    'paymentMode' : PaymentMode,
    'category' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const GuestCheckInStatus = IDL.Variant({
    'checkedIn' : IDL.Null,
    'checkedOut' : IDL.Null,
  });
  const GuestCheckIn = IDL.Record({
    'id' : IDL.Text,
    'status' : GuestCheckInStatus,
    'createdAt' : IDL.Int,
    'checkInDate' : IDL.Text,
    'guestName' : IDL.Text,
    'roomNumber' : IDL.Text,
    'children' : IDL.Nat,
    'idNumber' : IDL.Text,
    'totalAmount' : IDL.Float64,
    'notes' : IDL.Text,
    'advancePaid' : IDL.Float64,
    'adults' : IDL.Nat,
    'expectedCheckOut' : IDL.Text,
    'phone' : IDL.Text,
    'idType' : IDL.Text,
    'actualCheckOut' : IDL.Text,
  });
  const RoomFoodOrder = IDL.Record({
    'id' : IDL.Text,
    'roomNumber' : IDL.Text,
    'guestName' : IDL.Text,
    'items' : IDL.Vec(OrderItem),
    'totalAmount' : IDL.Float64,
    'gstAmount' : IDL.Float64,
    'paymentMode' : PaymentMode,
    'notes' : IDL.Text,
    'createdAt' : IDL.Int,
    'isPaid' : IDL.Bool,
  });
  const RoomInvoice = IDL.Record({
    'id' : IDL.Text,
    'guestCheckInId' : IDL.Text,
    'guestName' : IDL.Text,
    'roomNumber' : IDL.Text,
    'roomType' : IDL.Text,
    'checkInDate' : IDL.Text,
    'checkOutDate' : IDL.Text,
    'nights' : IDL.Nat,
    'roomRate' : IDL.Float64,
    'roomCharges' : IDL.Float64,
    'foodCharges' : IDL.Float64,
    'otherCharges' : IDL.Float64,
    'discount' : IDL.Float64,
    'gstPercent' : IDL.Float64,
    'gstAmount' : IDL.Float64,
    'totalAmount' : IDL.Float64,
    'advancePaid' : IDL.Float64,
    'balanceDue' : IDL.Float64,
    'paymentMode' : PaymentMode,
    'notes' : IDL.Text,
    'createdAt' : IDL.Int,
  });
  const RestaurantInventory = IDL.Record({
    'id' : IDL.Text,
    'costPerUnit' : IDL.Float64,
    'stockQty' : IDL.Float64,
    'name' : IDL.Text,
    'unit' : IDL.Text,
    'reorderLevel' : IDL.Float64,
  });
  const MenuCategory = IDL.Record({
    'id' : IDL.Text,
    'sortOrder' : IDL.Nat,
    'name' : IDL.Text,
  });
  const MenuItem = IDL.Record({
    'id' : IDL.Text,
    'categoryId' : IDL.Text,
    'name' : IDL.Text,
    'gstPercent' : IDL.Float64,
    'isAvailable' : IDL.Bool,
    'description' : IDL.Text,
    'isVeg' : IDL.Bool,
    'price' : IDL.Float64,
  });
  const OrderStatus = IDL.Variant({
    'pending' : IDL.Null,
    'served' : IDL.Null,
    'cooking' : IDL.Null,
    'billed' : IDL.Null,
  });
  const RestaurantOrder = IDL.Record({
    'id' : IDL.Text,
    'customerName' : IDL.Opt(IDL.Text),
    'status' : OrderStatus,
    'createdAt' : IDL.Int,
    'tableId' : IDL.Text,
    'gstAmount' : IDL.Float64,
    'totalAmount' : IDL.Float64,
    'items' : IDL.Vec(OrderItem),
  });
  const RestaurantReceipt = IDL.Record({
    'id' : IDL.Text,
    'source' : IDL.Text,
    'date' : IDL.Int,
    'note' : IDL.Text,
    'paymentMode' : PaymentMode,
    'amount' : IDL.Float64,
  });
  const Type = IDL.Variant({
    'contact' : IDL.Null,
    'banquet' : IDL.Null,
    'booking' : IDL.Null,
  });
  const ContactInquiry = IDL.Record({
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
  });
  const BanquetInquiry = IDL.Record({
    'guestCount' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
    'eventDate' : IDL.Text,
    'eventType' : IDL.Text,
  });
  const BookingInquiry = IDL.Record({
    'checkIn' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'checkOut' : IDL.Text,
    'phone' : IDL.Text,
    'guests' : IDL.Nat,
    'roomType' : IDL.Text,
  });
  const InquiryDetails = IDL.Variant({
    'contact' : ContactInquiry,
    'banquet' : BanquetInquiry,
    'booking' : BookingInquiry,
  });
  const Inquiry = IDL.Record({
    'id' : IDL.Nat,
    'inquiryType' : Type,
    'timestamp' : IDL.Int,
    'details' : InquiryDetails,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const TableStatus = IDL.Variant({
    'occupied' : IDL.Null,
    'free' : IDL.Null,
    'reserved' : IDL.Null,
  });
  const RestaurantTable = IDL.Record({
    'id' : IDL.Text,
    'status' : TableStatus,
    'seats' : IDL.Nat,
    'currentOrderId' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBanquetBill' : IDL.Func([BanquetBill], [], []),
    'createBill' : IDL.Func([RestaurantBill], [], []),
    'createCustomer' : IDL.Func([RestaurantCustomer], [], []),
    'createDue' : IDL.Func([RestaurantDue], [], []),
    'createExpense' : IDL.Func([RestaurantExpense], [], []),
    'createGuestCheckIn' : IDL.Func([GuestCheckIn], [], []),
    'createInventoryItem' : IDL.Func([RestaurantInventory], [], []),
    'createMenuCategory' : IDL.Func([MenuCategory], [], []),
    'createMenuItem' : IDL.Func([MenuItem], [], []),
    'createOrder' : IDL.Func([RestaurantOrder], [], []),
    'createReceipt' : IDL.Func([RestaurantReceipt], [], []),
    'createRoomFoodOrder' : IDL.Func([RoomFoodOrder], [], []),
    'createRoomInvoice' : IDL.Func([RoomInvoice], [], []),
    'deleteBanquetBill' : IDL.Func([IDL.Text], [], []),
    'deleteBill' : IDL.Func([IDL.Text], [], []),
    'deleteCustomer' : IDL.Func([IDL.Text], [], []),
    'deleteDue' : IDL.Func([IDL.Text], [], []),
    'deleteExpense' : IDL.Func([IDL.Text], [], []),
    'deleteGuestCheckIn' : IDL.Func([IDL.Text], [], []),
    'deleteInventoryItem' : IDL.Func([IDL.Text], [], []),
    'deleteMenuCategory' : IDL.Func([IDL.Text], [], []),
    'deleteMenuItem' : IDL.Func([IDL.Text], [], []),
    'deleteOrder' : IDL.Func([IDL.Text], [], []),
    'deleteReceipt' : IDL.Func([IDL.Text], [], []),
    'deleteRoomFoodOrder' : IDL.Func([IDL.Text], [], []),
    'deleteTable' : IDL.Func([IDL.Text], [], []),
    'getAllGuestCheckIns' : IDL.Func([], [IDL.Vec(GuestCheckIn)], ['query']),
    'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getAllRoomFoodOrders' : IDL.Func([], [IDL.Vec(RoomFoodOrder)], ['query']),
    'getAllRoomInvoices' : IDL.Func([], [IDL.Vec(RoomInvoice)], ['query']),
    'getBanquetBill' : IDL.Func([IDL.Text], [IDL.Opt(BanquetBill)], ['query']),
    'getBanquetBills' : IDL.Func([], [IDL.Vec(BanquetBill)], ['query']),
    'getBill' : IDL.Func([IDL.Text], [IDL.Opt(RestaurantBill)], ['query']),
    'getBills' : IDL.Func([], [IDL.Vec(RestaurantBill)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomer' : IDL.Func([IDL.Text], [IDL.Opt(RestaurantCustomer)], ['query']),
    'getCustomers' : IDL.Func([], [IDL.Vec(RestaurantCustomer)], ['query']),
    'getDue' : IDL.Func([IDL.Text], [IDL.Opt(RestaurantDue)], ['query']),
    'getDues' : IDL.Func([], [IDL.Vec(RestaurantDue)], ['query']),
    'getExpense' : IDL.Func([IDL.Text], [IDL.Opt(RestaurantExpense)], ['query']),
    'getExpenses' : IDL.Func([], [IDL.Vec(RestaurantExpense)], ['query']),
    'getGuestCheckIn' : IDL.Func([IDL.Text], [IDL.Opt(GuestCheckIn)], ['query']),
    'getInventoryItem' : IDL.Func([IDL.Text], [IDL.Opt(RestaurantInventory)], ['query']),
    'getInventoryItems' : IDL.Func([], [IDL.Vec(RestaurantInventory)], ['query']),
    'getMenuCategories' : IDL.Func([], [IDL.Vec(MenuCategory)], ['query']),
    'getMenuCategory' : IDL.Func([IDL.Text], [IDL.Opt(MenuCategory)], ['query']),
    'getMenuItem' : IDL.Func([IDL.Text], [IDL.Opt(MenuItem)], ['query']),
    'getMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'getOrder' : IDL.Func([IDL.Text], [IDL.Opt(RestaurantOrder)], ['query']),
    'getOrders' : IDL.Func([], [IDL.Vec(RestaurantOrder)], ['query']),
    'getReceipt' : IDL.Func([IDL.Text], [IDL.Opt(RestaurantReceipt)], ['query']),
    'getReceipts' : IDL.Func([], [IDL.Vec(RestaurantReceipt)], ['query']),
    'getRoomFoodOrder' : IDL.Func([IDL.Text], [IDL.Opt(RoomFoodOrder)], ['query']),
    'getRoomInvoice' : IDL.Func([IDL.Text], [IDL.Opt(RoomInvoice)], ['query']),
    'getTable' : IDL.Func([IDL.Text], [IDL.Opt(RestaurantTable)], ['query']),
    'getTables' : IDL.Func([], [IDL.Vec(RestaurantTable)], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(UserProfile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitBanquet' : IDL.Func([BanquetInquiry], [IDL.Nat], []),
    'submitBooking' : IDL.Func([BookingInquiry], [IDL.Nat], []),
    'submitContact' : IDL.Func([ContactInquiry], [IDL.Nat], []),
    'updateBanquetBill' : IDL.Func([BanquetBill], [], []),
    'updateBill' : IDL.Func([RestaurantBill], [], []),
    'updateCustomer' : IDL.Func([RestaurantCustomer], [], []),
    'updateDue' : IDL.Func([RestaurantDue], [], []),
    'updateExpense' : IDL.Func([RestaurantExpense], [], []),
    'updateGuestCheckIn' : IDL.Func([GuestCheckIn], [], []),
    'updateInventoryItem' : IDL.Func([RestaurantInventory], [], []),
    'updateMenuCategory' : IDL.Func([MenuCategory], [], []),
    'updateMenuItem' : IDL.Func([MenuItem], [], []),
    'updateOrder' : IDL.Func([RestaurantOrder], [], []),
    'updateReceipt' : IDL.Func([RestaurantReceipt], [], []),
    'updateRoomFoodOrder' : IDL.Func([RoomFoodOrder], [], []),
    'updateRoomInvoice' : IDL.Func([RoomInvoice], [], []),
    'updateTable' : IDL.Func([RestaurantTable], [], []),
  });
};

export const init = ({ IDL }) => { return []; };
