/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BanquetBill {
  'id' : string,
  'contactName' : string,
  'guestCount' : bigint,
  'createdAt' : bigint,
  'gstPercent' : number,
  'hallName' : string,
  'totalAmount' : number,
  'paymentMode' : PaymentMode,
  'extraCharges' : number,
  'perPlateRate' : number,
  'eventName' : string,
  'contactPhone' : string,
}
export interface BanquetInquiry {
  'guestCount' : bigint,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
  'phone' : string,
  'eventDate' : string,
  'eventType' : string,
}
export interface BookingInquiry {
  'checkIn' : string,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
  'checkOut' : string,
  'phone' : string,
  'guests' : bigint,
  'roomType' : string,
}
export interface ContactInquiry {
  'subject' : string,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
  'phone' : string,
}
export interface GuestCheckIn {
  'id' : string,
  'status' : GuestCheckInStatus,
  'createdAt' : bigint,
  'checkInDate' : string,
  'guestName' : string,
  'roomNumber' : string,
  'children' : bigint,
  'idNumber' : string,
  'totalAmount' : number,
  'notes' : string,
  'advancePaid' : number,
  'adults' : bigint,
  'expectedCheckOut' : string,
  'phone' : string,
  'idType' : string,
  'actualCheckOut' : string,
}
export type GuestCheckInStatus = { 'checkedIn' : null } |
  { 'checkedOut' : null };
export interface Inquiry {
  'id' : bigint,
  'inquiryType' : Type,
  'timestamp' : bigint,
  'details' : InquiryDetails,
}
export type InquiryDetails = { 'contact' : ContactInquiry } |
  { 'banquet' : BanquetInquiry } |
  { 'booking' : BookingInquiry };
export interface MenuCategory {
  'id' : string,
  'sortOrder' : bigint,
  'name' : string,
}
export interface MenuItem {
  'id' : string,
  'categoryId' : string,
  'name' : string,
  'gstPercent' : number,
  'isAvailable' : boolean,
  'description' : string,
  'isVeg' : boolean,
  'price' : number,
}
export interface OrderItem {
  'qty' : bigint,
  'name' : string,
  'notes' : string,
  'price' : number,
  'menuItemId' : string,
}
export type OrderStatus = { 'pending' : null } |
  { 'served' : null } |
  { 'cooking' : null } |
  { 'billed' : null };
export type PaymentMode = { 'upi' : null } |
  { 'card' : null } |
  { 'cash' : null };
export interface RestaurantBill {
  'id' : string,
  'customerName' : [] | [string],
  'createdAt' : bigint,
  'tableId' : string,
  'gstAmount' : number,
  'orderId' : string,
  'totalAmount' : number,
  'discount' : number,
  'paymentMode' : PaymentMode,
  'items' : Array<OrderItem>,
  'subtotal' : number,
}
export interface RestaurantCustomer {
  'id' : string,
  'name' : string,
  'email' : string,
  'loyaltyPoints' : bigint,
  'totalSpend' : number,
  'address' : string,
  'phone' : string,
}
export interface RestaurantDue {
  'id' : string,
  'customerName' : string,
  'dueDate' : bigint,
  'description' : string,
  'isPaid' : boolean,
  'customerId' : string,
  'amount' : number,
}
export interface RestaurantExpense {
  'id' : string,
  'date' : bigint,
  'description' : string,
  'paymentMode' : PaymentMode,
  'category' : string,
  'amount' : number,
}
export interface RestaurantInventory {
  'id' : string,
  'costPerUnit' : number,
  'stockQty' : number,
  'name' : string,
  'unit' : string,
  'reorderLevel' : number,
}
export interface RestaurantOrder {
  'id' : string,
  'customerName' : [] | [string],
  'status' : OrderStatus,
  'createdAt' : bigint,
  'tableId' : string,
  'gstAmount' : number,
  'totalAmount' : number,
  'items' : Array<OrderItem>,
}
export interface RestaurantReceipt {
  'id' : string,
  'source' : string,
  'date' : bigint,
  'note' : string,
  'paymentMode' : PaymentMode,
  'amount' : number,
}
export interface RestaurantTable {
  'id' : string,
  'status' : TableStatus,
  'seats' : bigint,
  'currentOrderId' : [] | [string],
}
export interface RoomFoodOrder {
  'id' : string,
  'roomNumber' : string,
  'guestName' : string,
  'items' : Array<OrderItem>,
  'totalAmount' : number,
  'gstAmount' : number,
  'paymentMode' : PaymentMode,
  'notes' : string,
  'createdAt' : bigint,
  'isPaid' : boolean,
}
export interface RoomInvoice {
  'id' : string,
  'guestCheckInId' : string,
  'guestName' : string,
  'roomNumber' : string,
  'roomType' : string,
  'checkInDate' : string,
  'checkOutDate' : string,
  'nights' : bigint,
  'roomRate' : number,
  'roomCharges' : number,
  'foodCharges' : number,
  'otherCharges' : number,
  'discount' : number,
  'gstPercent' : number,
  'gstAmount' : number,
  'totalAmount' : number,
  'advancePaid' : number,
  'balanceDue' : number,
  'paymentMode' : PaymentMode,
  'notes' : string,
  'createdAt' : bigint,
}
export type TableStatus = { 'occupied' : null } |
  { 'free' : null } |
  { 'reserved' : null };
export type Type = { 'contact' : null } |
  { 'banquet' : null } |
  { 'booking' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBanquetBill' : ActorMethod<[BanquetBill], undefined>,
  'createBill' : ActorMethod<[RestaurantBill], undefined>,
  'createCustomer' : ActorMethod<[RestaurantCustomer], undefined>,
  'createDue' : ActorMethod<[RestaurantDue], undefined>,
  'createExpense' : ActorMethod<[RestaurantExpense], undefined>,
  'createGuestCheckIn' : ActorMethod<[GuestCheckIn], undefined>,
  'createInventoryItem' : ActorMethod<[RestaurantInventory], undefined>,
  'createMenuCategory' : ActorMethod<[MenuCategory], undefined>,
  'createMenuItem' : ActorMethod<[MenuItem], undefined>,
  'createOrder' : ActorMethod<[RestaurantOrder], undefined>,
  'createReceipt' : ActorMethod<[RestaurantReceipt], undefined>,
  'createRoomFoodOrder' : ActorMethod<[RoomFoodOrder], undefined>,
  'createRoomInvoice' : ActorMethod<[RoomInvoice], undefined>,
  'deleteBanquetBill' : ActorMethod<[string], undefined>,
  'deleteBill' : ActorMethod<[string], undefined>,
  'deleteCustomer' : ActorMethod<[string], undefined>,
  'deleteDue' : ActorMethod<[string], undefined>,
  'deleteExpense' : ActorMethod<[string], undefined>,
  'deleteGuestCheckIn' : ActorMethod<[string], undefined>,
  'deleteInventoryItem' : ActorMethod<[string], undefined>,
  'deleteMenuCategory' : ActorMethod<[string], undefined>,
  'deleteMenuItem' : ActorMethod<[string], undefined>,
  'deleteOrder' : ActorMethod<[string], undefined>,
  'deleteReceipt' : ActorMethod<[string], undefined>,
  'deleteRoomFoodOrder' : ActorMethod<[string], undefined>,
  'deleteTable' : ActorMethod<[string], undefined>,
  'getAllGuestCheckIns' : ActorMethod<[], Array<GuestCheckIn>>,
  'getAllInquiries' : ActorMethod<[], Array<Inquiry>>,
  'getAllRoomFoodOrders' : ActorMethod<[], Array<RoomFoodOrder>>,
  'getAllRoomInvoices' : ActorMethod<[], Array<RoomInvoice>>,
  'getBanquetBill' : ActorMethod<[string], [] | [BanquetBill]>,
  'getBanquetBills' : ActorMethod<[], Array<BanquetBill>>,
  'getBill' : ActorMethod<[string], [] | [RestaurantBill]>,
  'getBills' : ActorMethod<[], Array<RestaurantBill>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomer' : ActorMethod<[string], [] | [RestaurantCustomer]>,
  'getCustomers' : ActorMethod<[], Array<RestaurantCustomer>>,
  'getDue' : ActorMethod<[string], [] | [RestaurantDue]>,
  'getDues' : ActorMethod<[], Array<RestaurantDue>>,
  'getExpense' : ActorMethod<[string], [] | [RestaurantExpense]>,
  'getExpenses' : ActorMethod<[], Array<RestaurantExpense>>,
  'getGuestCheckIn' : ActorMethod<[string], [] | [GuestCheckIn]>,
  'getInventoryItem' : ActorMethod<[string], [] | [RestaurantInventory]>,
  'getInventoryItems' : ActorMethod<[], Array<RestaurantInventory>>,
  'getMenuCategories' : ActorMethod<[], Array<MenuCategory>>,
  'getMenuCategory' : ActorMethod<[string], [] | [MenuCategory]>,
  'getMenuItem' : ActorMethod<[string], [] | [MenuItem]>,
  'getMenuItems' : ActorMethod<[], Array<MenuItem>>,
  'getOrder' : ActorMethod<[string], [] | [RestaurantOrder]>,
  'getOrders' : ActorMethod<[], Array<RestaurantOrder>>,
  'getReceipt' : ActorMethod<[string], [] | [RestaurantReceipt]>,
  'getReceipts' : ActorMethod<[], Array<RestaurantReceipt>>,
  'getRoomFoodOrder' : ActorMethod<[string], [] | [RoomFoodOrder]>,
  'getRoomInvoice' : ActorMethod<[string], [] | [RoomInvoice]>,
  'getTable' : ActorMethod<[string], [] | [RestaurantTable]>,
  'getTables' : ActorMethod<[], Array<RestaurantTable>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitBanquet' : ActorMethod<[BanquetInquiry], bigint>,
  'submitBooking' : ActorMethod<[BookingInquiry], bigint>,
  'submitContact' : ActorMethod<[ContactInquiry], bigint>,
  'updateBanquetBill' : ActorMethod<[BanquetBill], undefined>,
  'updateBill' : ActorMethod<[RestaurantBill], undefined>,
  'updateCustomer' : ActorMethod<[RestaurantCustomer], undefined>,
  'updateDue' : ActorMethod<[RestaurantDue], undefined>,
  'updateExpense' : ActorMethod<[RestaurantExpense], undefined>,
  'updateGuestCheckIn' : ActorMethod<[GuestCheckIn], undefined>,
  'updateInventoryItem' : ActorMethod<[RestaurantInventory], undefined>,
  'updateMenuCategory' : ActorMethod<[MenuCategory], undefined>,
  'updateMenuItem' : ActorMethod<[MenuItem], undefined>,
  'updateOrder' : ActorMethod<[RestaurantOrder], undefined>,
  'updateReceipt' : ActorMethod<[RestaurantReceipt], undefined>,
  'updateRoomFoodOrder' : ActorMethod<[RoomFoodOrder], undefined>,
  'updateRoomInvoice' : ActorMethod<[RoomInvoice], undefined>,
  'updateTable' : ActorMethod<[RestaurantTable], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
