/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface RestaurantDue {
    id: string;
    customerName: string;
    dueDate: bigint;
    description: string;
    isPaid: boolean;
    customerId: string;
    amount: number;
}
export interface MenuCategory {
    id: string;
    sortOrder: bigint;
    name: string;
}
export interface RestaurantBill {
    id: string;
    customerName?: string;
    createdAt: bigint;
    tableId: string;
    gstAmount: number;
    orderId: string;
    totalAmount: number;
    discount: number;
    paymentMode: PaymentMode;
    items: Array<OrderItem>;
    subtotal: number;
}
export interface RestaurantTable {
    id: string;
    status: TableStatus;
    seats: bigint;
    currentOrderId?: string;
}
export interface OrderItem {
    qty: bigint;
    name: string;
    notes: string;
    price: number;
    menuItemId: string;
}
export interface GuestCheckIn {
    id: string;
    status: GuestCheckInStatus;
    createdAt: bigint;
    checkInDate: string;
    guestName: string;
    roomNumber: string;
    children: bigint;
    idNumber: string;
    totalAmount: number;
    notes: string;
    advancePaid: number;
    adults: bigint;
    expectedCheckOut: string;
    phone: string;
    idType: string;
    actualCheckOut: string;
}
export interface BookingInquiry {
    checkIn: string;
    name: string;
    email: string;
    message: string;
    timestamp: bigint;
    checkOut: string;
    phone: string;
    guests: bigint;
    roomType: string;
}
export interface RestaurantOrder {
    id: string;
    customerName?: string;
    status: OrderStatus;
    createdAt: bigint;
    tableId: string;
    gstAmount: number;
    totalAmount: number;
    items: Array<OrderItem>;
}
export interface RestaurantCustomer {
    id: string;
    name: string;
    email: string;
    loyaltyPoints: bigint;
    totalSpend: number;
    address: string;
    phone: string;
}
export interface RestaurantExpense {
    id: string;
    date: bigint;
    description: string;
    paymentMode: PaymentMode;
    category: string;
    amount: number;
}
export type InquiryDetails = {
    __kind__: "contact";
    contact: ContactInquiry;
} | {
    __kind__: "banquet";
    banquet: BanquetInquiry;
} | {
    __kind__: "booking";
    booking: BookingInquiry;
};
export interface BanquetInquiry {
    guestCount: bigint;
    name: string;
    email: string;
    message: string;
    timestamp: bigint;
    phone: string;
    eventDate: string;
    eventType: string;
}
export interface MenuItem {
    id: string;
    categoryId: string;
    name: string;
    gstPercent: number;
    isAvailable: boolean;
    description: string;
    isVeg: boolean;
    price: number;
}
export interface BanquetBill {
    id: string;
    contactName: string;
    guestCount: bigint;
    createdAt: bigint;
    gstPercent: number;
    hallName: string;
    totalAmount: number;
    paymentMode: PaymentMode;
    extraCharges: number;
    perPlateRate: number;
    eventName: string;
    contactPhone: string;
}
export interface RestaurantReceipt {
    id: string;
    source: string;
    date: bigint;
    note: string;
    paymentMode: PaymentMode;
    amount: number;
}
export interface RestaurantInventory {
    id: string;
    costPerUnit: number;
    stockQty: number;
    name: string;
    unit: string;
    reorderLevel: number;
}
export interface Inquiry {
    id: bigint;
    inquiryType: Type;
    timestamp: bigint;
    details: InquiryDetails;
}
export interface ContactInquiry {
    subject: string;
    name: string;
    email: string;
    message: string;
    timestamp: bigint;
    phone: string;
}
export interface UserProfile {
    name: string;
}
export enum GuestCheckInStatus {
    checkedIn = "checkedIn",
    checkedOut = "checkedOut"
}
export enum OrderStatus {
    pending = "pending",
    served = "served",
    cooking = "cooking",
    billed = "billed"
}
export enum PaymentMode {
    upi = "upi",
    card = "card",
    cash = "cash"
}
export enum TableStatus {
    occupied = "occupied",
    free = "free",
    reserved = "reserved"
}
export enum Type {
    contact = "contact",
    banquet = "banquet",
    booking = "booking"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createBanquetBill(bill: BanquetBill): Promise<void>;
    createBill(bill: RestaurantBill): Promise<void>;
    createCustomer(customer: RestaurantCustomer): Promise<void>;
    createDue(due: RestaurantDue): Promise<void>;
    createExpense(expense: RestaurantExpense): Promise<void>;
    createGuestCheckIn(checkIn: GuestCheckIn): Promise<void>;
    createInventoryItem(item: RestaurantInventory): Promise<void>;
    createMenuCategory(category: MenuCategory): Promise<void>;
    createMenuItem(item: MenuItem): Promise<void>;
    createOrder(order: RestaurantOrder): Promise<void>;
    createReceipt(receipt: RestaurantReceipt): Promise<void>;
    deleteBanquetBill(id: string): Promise<void>;
    deleteBill(id: string): Promise<void>;
    deleteCustomer(id: string): Promise<void>;
    deleteDue(id: string): Promise<void>;
    deleteExpense(id: string): Promise<void>;
    deleteGuestCheckIn(id: string): Promise<void>;
    deleteInventoryItem(id: string): Promise<void>;
    deleteMenuCategory(id: string): Promise<void>;
    deleteMenuItem(id: string): Promise<void>;
    deleteOrder(id: string): Promise<void>;
    deleteReceipt(id: string): Promise<void>;
    deleteTable(id: string): Promise<void>;
    getAllGuestCheckIns(): Promise<Array<GuestCheckIn>>;
    getAllInquiries(): Promise<Array<Inquiry>>;
    getBanquetBill(id: string): Promise<BanquetBill | null>;
    getBanquetBills(): Promise<Array<BanquetBill>>;
    getBill(id: string): Promise<RestaurantBill | null>;
    getBills(): Promise<Array<RestaurantBill>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCustomer(id: string): Promise<RestaurantCustomer | null>;
    getCustomers(): Promise<Array<RestaurantCustomer>>;
    getDue(id: string): Promise<RestaurantDue | null>;
    getDues(): Promise<Array<RestaurantDue>>;
    getExpense(id: string): Promise<RestaurantExpense | null>;
    getExpenses(): Promise<Array<RestaurantExpense>>;
    getGuestCheckIn(id: string): Promise<GuestCheckIn | null>;
    getInventoryItem(id: string): Promise<RestaurantInventory | null>;
    getInventoryItems(): Promise<Array<RestaurantInventory>>;
    getMenuCategories(): Promise<Array<MenuCategory>>;
    getMenuCategory(id: string): Promise<MenuCategory | null>;
    getMenuItem(id: string): Promise<MenuItem | null>;
    getMenuItems(): Promise<Array<MenuItem>>;
    getOrder(id: string): Promise<RestaurantOrder | null>;
    getOrders(): Promise<Array<RestaurantOrder>>;
    getReceipt(id: string): Promise<RestaurantReceipt | null>;
    getReceipts(): Promise<Array<RestaurantReceipt>>;
    getTable(id: string): Promise<RestaurantTable | null>;
    getTables(): Promise<Array<RestaurantTable>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitBanquet(inquiry: BanquetInquiry): Promise<bigint>;
    submitBooking(inquiry: BookingInquiry): Promise<bigint>;
    submitContact(inquiry: ContactInquiry): Promise<bigint>;
    updateBanquetBill(bill: BanquetBill): Promise<void>;
    updateBill(bill: RestaurantBill): Promise<void>;
    updateCustomer(customer: RestaurantCustomer): Promise<void>;
    updateDue(due: RestaurantDue): Promise<void>;
    updateExpense(expense: RestaurantExpense): Promise<void>;
    updateGuestCheckIn(checkIn: GuestCheckIn): Promise<void>;
    updateInventoryItem(item: RestaurantInventory): Promise<void>;
    updateMenuCategory(category: MenuCategory): Promise<void>;
    updateMenuItem(item: MenuItem): Promise<void>;
    updateOrder(order: RestaurantOrder): Promise<void>;
    updateReceipt(receipt: RestaurantReceipt): Promise<void>;
    updateTable(table: RestaurantTable): Promise<void>;
}
import type { BanquetBill as _BanquetBill, BanquetInquiry as _BanquetInquiry, BookingInquiry as _BookingInquiry, ContactInquiry as _ContactInquiry, GuestCheckIn as _GuestCheckIn, GuestCheckInStatus as _GuestCheckInStatus, Inquiry as _Inquiry, InquiryDetails as _InquiryDetails, MenuCategory as _MenuCategory, MenuItem as _MenuItem, OrderItem as _OrderItem, OrderStatus as _OrderStatus, PaymentMode as _PaymentMode, RestaurantBill as _RestaurantBill, RestaurantCustomer as _RestaurantCustomer, RestaurantDue as _RestaurantDue, RestaurantExpense as _RestaurantExpense, RestaurantInventory as _RestaurantInventory, RestaurantOrder as _RestaurantOrder, RestaurantReceipt as _RestaurantReceipt, RestaurantTable as _RestaurantTable, TableStatus as _TableStatus, Type as _Type, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createBanquetBill(arg0: BanquetBill): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createBanquetBill(to_candid_BanquetBill_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBanquetBill(to_candid_BanquetBill_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createBill(arg0: RestaurantBill): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createBill(to_candid_RestaurantBill_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBill(to_candid_RestaurantBill_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createCustomer(arg0: RestaurantCustomer): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createCustomer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCustomer(arg0);
            return result;
        }
    }
    async createDue(arg0: RestaurantDue): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createDue(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDue(arg0);
            return result;
        }
    }
    async createExpense(arg0: RestaurantExpense): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createExpense(to_candid_RestaurantExpense_n9(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createExpense(to_candid_RestaurantExpense_n9(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createGuestCheckIn(arg0: GuestCheckIn): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createGuestCheckIn(to_candid_GuestCheckIn_n11(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGuestCheckIn(to_candid_GuestCheckIn_n11(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createInventoryItem(arg0: RestaurantInventory): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createInventoryItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createInventoryItem(arg0);
            return result;
        }
    }
    async createMenuCategory(arg0: MenuCategory): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createMenuCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMenuCategory(arg0);
            return result;
        }
    }
    async createMenuItem(arg0: MenuItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createMenuItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMenuItem(arg0);
            return result;
        }
    }
    async createOrder(arg0: RestaurantOrder): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrder(to_candid_RestaurantOrder_n15(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrder(to_candid_RestaurantOrder_n15(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createReceipt(arg0: RestaurantReceipt): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createReceipt(to_candid_RestaurantReceipt_n19(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createReceipt(to_candid_RestaurantReceipt_n19(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteBanquetBill(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBanquetBill(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBanquetBill(arg0);
            return result;
        }
    }
    async deleteBill(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBill(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBill(arg0);
            return result;
        }
    }
    async deleteCustomer(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCustomer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCustomer(arg0);
            return result;
        }
    }
    async deleteDue(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDue(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDue(arg0);
            return result;
        }
    }
    async deleteExpense(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteExpense(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteExpense(arg0);
            return result;
        }
    }
    async deleteGuestCheckIn(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGuestCheckIn(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGuestCheckIn(arg0);
            return result;
        }
    }
    async deleteInventoryItem(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteInventoryItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteInventoryItem(arg0);
            return result;
        }
    }
    async deleteMenuCategory(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMenuCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMenuCategory(arg0);
            return result;
        }
    }
    async deleteMenuItem(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMenuItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMenuItem(arg0);
            return result;
        }
    }
    async deleteOrder(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteOrder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteOrder(arg0);
            return result;
        }
    }
    async deleteReceipt(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteReceipt(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteReceipt(arg0);
            return result;
        }
    }
    async deleteTable(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTable(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTable(arg0);
            return result;
        }
    }
    async getAllGuestCheckIns(): Promise<Array<GuestCheckIn>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllGuestCheckIns();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllGuestCheckIns();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllInquiries(): Promise<Array<Inquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInquiries();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInquiries();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBanquetBill(arg0: string): Promise<BanquetBill | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBanquetBill(arg0);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBanquetBill(arg0);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBanquetBills(): Promise<Array<BanquetBill>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBanquetBills();
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBanquetBills();
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBill(arg0: string): Promise<RestaurantBill | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBill(arg0);
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBill(arg0);
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBills(): Promise<Array<RestaurantBill>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBills();
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBills();
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomer(arg0: string): Promise<RestaurantCustomer | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomer(arg0);
                return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomer(arg0);
            return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomers(): Promise<Array<RestaurantCustomer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomers();
            return result;
        }
    }
    async getDue(arg0: string): Promise<RestaurantDue | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDue(arg0);
                return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDue(arg0);
            return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDues(): Promise<Array<RestaurantDue>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDues();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDues();
            return result;
        }
    }
    async getExpense(arg0: string): Promise<RestaurantExpense | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpense(arg0);
                return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpense(arg0);
            return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExpenses(): Promise<Array<RestaurantExpense>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpenses();
                return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpenses();
            return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGuestCheckIn(arg0: string): Promise<GuestCheckIn | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGuestCheckIn(arg0);
                return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGuestCheckIn(arg0);
            return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInventoryItem(arg0: string): Promise<RestaurantInventory | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getInventoryItem(arg0);
                return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInventoryItem(arg0);
            return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInventoryItems(): Promise<Array<RestaurantInventory>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInventoryItems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInventoryItems();
            return result;
        }
    }
    async getMenuCategories(): Promise<Array<MenuCategory>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMenuCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMenuCategories();
            return result;
        }
    }
    async getMenuCategory(arg0: string): Promise<MenuCategory | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMenuCategory(arg0);
                return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMenuCategory(arg0);
            return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMenuItem(arg0: string): Promise<MenuItem | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMenuItem(arg0);
                return from_candid_opt_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMenuItem(arg0);
            return from_candid_opt_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMenuItems(): Promise<Array<MenuItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMenuItems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMenuItems();
            return result;
        }
    }
    async getOrder(arg0: string): Promise<RestaurantOrder | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrder(arg0);
                return from_candid_opt_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrder(arg0);
            return from_candid_opt_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrders(): Promise<Array<RestaurantOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrders();
                return from_candid_vec_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrders();
            return from_candid_vec_n62(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReceipt(arg0: string): Promise<RestaurantReceipt | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getReceipt(arg0);
                return from_candid_opt_n63(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReceipt(arg0);
            return from_candid_opt_n63(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReceipts(): Promise<Array<RestaurantReceipt>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReceipts();
                return from_candid_vec_n66(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReceipts();
            return from_candid_vec_n66(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTable(arg0: string): Promise<RestaurantTable | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTable(arg0);
                return from_candid_opt_n67(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTable(arg0);
            return from_candid_opt_n67(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTables(): Promise<Array<RestaurantTable>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTables();
                return from_candid_vec_n72(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTables();
            return from_candid_vec_n72(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async submitBanquet(arg0: BanquetInquiry): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitBanquet(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitBanquet(arg0);
            return result;
        }
    }
    async submitBooking(arg0: BookingInquiry): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitBooking(arg0);
            return result;
        }
    }
    async submitContact(arg0: ContactInquiry): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContact(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContact(arg0);
            return result;
        }
    }
    async updateBanquetBill(arg0: BanquetBill): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBanquetBill(to_candid_BanquetBill_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBanquetBill(to_candid_BanquetBill_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateBill(arg0: RestaurantBill): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBill(to_candid_RestaurantBill_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBill(to_candid_RestaurantBill_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateCustomer(arg0: RestaurantCustomer): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCustomer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCustomer(arg0);
            return result;
        }
    }
    async updateDue(arg0: RestaurantDue): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDue(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDue(arg0);
            return result;
        }
    }
    async updateExpense(arg0: RestaurantExpense): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateExpense(to_candid_RestaurantExpense_n9(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateExpense(to_candid_RestaurantExpense_n9(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateGuestCheckIn(arg0: GuestCheckIn): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGuestCheckIn(to_candid_GuestCheckIn_n11(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGuestCheckIn(to_candid_GuestCheckIn_n11(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateInventoryItem(arg0: RestaurantInventory): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInventoryItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInventoryItem(arg0);
            return result;
        }
    }
    async updateMenuCategory(arg0: MenuCategory): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMenuCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMenuCategory(arg0);
            return result;
        }
    }
    async updateMenuItem(arg0: MenuItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMenuItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMenuItem(arg0);
            return result;
        }
    }
    async updateOrder(arg0: RestaurantOrder): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrder(to_candid_RestaurantOrder_n15(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrder(to_candid_RestaurantOrder_n15(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateReceipt(arg0: RestaurantReceipt): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateReceipt(to_candid_RestaurantReceipt_n19(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateReceipt(to_candid_RestaurantReceipt_n19(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateTable(arg0: RestaurantTable): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTable(to_candid_RestaurantTable_n73(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTable(to_candid_RestaurantTable_n73(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_BanquetBill_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BanquetBill): BanquetBill {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_GuestCheckInStatus_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GuestCheckInStatus): GuestCheckInStatus {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_GuestCheckIn_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GuestCheckIn): GuestCheckIn {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_InquiryDetails_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InquiryDetails): InquiryDetails {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_Inquiry_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Inquiry): Inquiry {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n61(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMode_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMode): PaymentMode {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_RestaurantBill_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RestaurantBill): RestaurantBill {
    return from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid_RestaurantExpense_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RestaurantExpense): RestaurantExpense {
    return from_candid_record_n51(_uploadFile, _downloadFile, value);
}
function from_candid_RestaurantOrder_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RestaurantOrder): RestaurantOrder {
    return from_candid_record_n59(_uploadFile, _downloadFile, value);
}
function from_candid_RestaurantReceipt_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RestaurantReceipt): RestaurantReceipt {
    return from_candid_record_n65(_uploadFile, _downloadFile, value);
}
function from_candid_RestaurantTable_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RestaurantTable): RestaurantTable {
    return from_candid_record_n69(_uploadFile, _downloadFile, value);
}
function from_candid_TableStatus_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TableStatus): TableStatus {
    return from_candid_variant_n71(_uploadFile, _downloadFile, value);
}
function from_candid_Type_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Type): Type {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BanquetBill]): BanquetBill | null {
    return value.length === 0 ? null : from_candid_BanquetBill_n34(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RestaurantBill]): RestaurantBill | null {
    return value.length === 0 ? null : from_candid_RestaurantBill_n40(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RestaurantCustomer]): RestaurantCustomer | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RestaurantDue]): RestaurantDue | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RestaurantExpense]): RestaurantExpense | null {
    return value.length === 0 ? null : from_candid_RestaurantExpense_n50(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_GuestCheckIn]): GuestCheckIn | null {
    return value.length === 0 ? null : from_candid_GuestCheckIn_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RestaurantInventory]): RestaurantInventory | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MenuCategory]): MenuCategory | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MenuItem]): MenuItem | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RestaurantOrder]): RestaurantOrder | null {
    return value.length === 0 ? null : from_candid_RestaurantOrder_n58(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RestaurantReceipt]): RestaurantReceipt | null {
    return value.length === 0 ? null : from_candid_RestaurantReceipt_n64(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RestaurantTable]): RestaurantTable | null {
    return value.length === 0 ? null : from_candid_RestaurantTable_n68(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _GuestCheckInStatus;
    createdAt: bigint;
    checkInDate: string;
    guestName: string;
    roomNumber: string;
    children: bigint;
    idNumber: string;
    totalAmount: number;
    notes: string;
    advancePaid: number;
    adults: bigint;
    expectedCheckOut: string;
    phone: string;
    idType: string;
    actualCheckOut: string;
}): {
    id: string;
    status: GuestCheckInStatus;
    createdAt: bigint;
    checkInDate: string;
    guestName: string;
    roomNumber: string;
    children: bigint;
    idNumber: string;
    totalAmount: number;
    notes: string;
    advancePaid: number;
    adults: bigint;
    expectedCheckOut: string;
    phone: string;
    idType: string;
    actualCheckOut: string;
} {
    return {
        id: value.id,
        status: from_candid_GuestCheckInStatus_n24(_uploadFile, _downloadFile, value.status),
        createdAt: value.createdAt,
        checkInDate: value.checkInDate,
        guestName: value.guestName,
        roomNumber: value.roomNumber,
        children: value.children,
        idNumber: value.idNumber,
        totalAmount: value.totalAmount,
        notes: value.notes,
        advancePaid: value.advancePaid,
        adults: value.adults,
        expectedCheckOut: value.expectedCheckOut,
        phone: value.phone,
        idType: value.idType,
        actualCheckOut: value.actualCheckOut
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    inquiryType: _Type;
    timestamp: bigint;
    details: _InquiryDetails;
}): {
    id: bigint;
    inquiryType: Type;
    timestamp: bigint;
    details: InquiryDetails;
} {
    return {
        id: value.id,
        inquiryType: from_candid_Type_n29(_uploadFile, _downloadFile, value.inquiryType),
        timestamp: value.timestamp,
        details: from_candid_InquiryDetails_n31(_uploadFile, _downloadFile, value.details)
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    contactName: string;
    guestCount: bigint;
    createdAt: bigint;
    gstPercent: number;
    hallName: string;
    totalAmount: number;
    paymentMode: _PaymentMode;
    extraCharges: number;
    perPlateRate: number;
    eventName: string;
    contactPhone: string;
}): {
    id: string;
    contactName: string;
    guestCount: bigint;
    createdAt: bigint;
    gstPercent: number;
    hallName: string;
    totalAmount: number;
    paymentMode: PaymentMode;
    extraCharges: number;
    perPlateRate: number;
    eventName: string;
    contactPhone: string;
} {
    return {
        id: value.id,
        contactName: value.contactName,
        guestCount: value.guestCount,
        createdAt: value.createdAt,
        gstPercent: value.gstPercent,
        hallName: value.hallName,
        totalAmount: value.totalAmount,
        paymentMode: from_candid_PaymentMode_n36(_uploadFile, _downloadFile, value.paymentMode),
        extraCharges: value.extraCharges,
        perPlateRate: value.perPlateRate,
        eventName: value.eventName,
        contactPhone: value.contactPhone
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    customerName: [] | [string];
    createdAt: bigint;
    tableId: string;
    gstAmount: number;
    orderId: string;
    totalAmount: number;
    discount: number;
    paymentMode: _PaymentMode;
    items: Array<_OrderItem>;
    subtotal: number;
}): {
    id: string;
    customerName?: string;
    createdAt: bigint;
    tableId: string;
    gstAmount: number;
    orderId: string;
    totalAmount: number;
    discount: number;
    paymentMode: PaymentMode;
    items: Array<OrderItem>;
    subtotal: number;
} {
    return {
        id: value.id,
        customerName: record_opt_to_undefined(from_candid_opt_n42(_uploadFile, _downloadFile, value.customerName)),
        createdAt: value.createdAt,
        tableId: value.tableId,
        gstAmount: value.gstAmount,
        orderId: value.orderId,
        totalAmount: value.totalAmount,
        discount: value.discount,
        paymentMode: from_candid_PaymentMode_n36(_uploadFile, _downloadFile, value.paymentMode),
        items: value.items,
        subtotal: value.subtotal
    };
}
function from_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    date: bigint;
    description: string;
    paymentMode: _PaymentMode;
    category: string;
    amount: number;
}): {
    id: string;
    date: bigint;
    description: string;
    paymentMode: PaymentMode;
    category: string;
    amount: number;
} {
    return {
        id: value.id,
        date: value.date,
        description: value.description,
        paymentMode: from_candid_PaymentMode_n36(_uploadFile, _downloadFile, value.paymentMode),
        category: value.category,
        amount: value.amount
    };
}
function from_candid_record_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    customerName: [] | [string];
    status: _OrderStatus;
    createdAt: bigint;
    tableId: string;
    gstAmount: number;
    totalAmount: number;
    items: Array<_OrderItem>;
}): {
    id: string;
    customerName?: string;
    status: OrderStatus;
    createdAt: bigint;
    tableId: string;
    gstAmount: number;
    totalAmount: number;
    items: Array<OrderItem>;
} {
    return {
        id: value.id,
        customerName: record_opt_to_undefined(from_candid_opt_n42(_uploadFile, _downloadFile, value.customerName)),
        status: from_candid_OrderStatus_n60(_uploadFile, _downloadFile, value.status),
        createdAt: value.createdAt,
        tableId: value.tableId,
        gstAmount: value.gstAmount,
        totalAmount: value.totalAmount,
        items: value.items
    };
}
function from_candid_record_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    source: string;
    date: bigint;
    note: string;
    paymentMode: _PaymentMode;
    amount: number;
}): {
    id: string;
    source: string;
    date: bigint;
    note: string;
    paymentMode: PaymentMode;
    amount: number;
} {
    return {
        id: value.id,
        source: value.source,
        date: value.date,
        note: value.note,
        paymentMode: from_candid_PaymentMode_n36(_uploadFile, _downloadFile, value.paymentMode),
        amount: value.amount
    };
}
function from_candid_record_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _TableStatus;
    seats: bigint;
    currentOrderId: [] | [string];
}): {
    id: string;
    status: TableStatus;
    seats: bigint;
    currentOrderId?: string;
} {
    return {
        id: value.id,
        status: from_candid_TableStatus_n70(_uploadFile, _downloadFile, value.status),
        seats: value.seats,
        currentOrderId: record_opt_to_undefined(from_candid_opt_n42(_uploadFile, _downloadFile, value.currentOrderId))
    };
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    checkedIn: null;
} | {
    checkedOut: null;
}): GuestCheckInStatus {
    return "checkedIn" in value ? GuestCheckInStatus.checkedIn : "checkedOut" in value ? GuestCheckInStatus.checkedOut : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    contact: null;
} | {
    banquet: null;
} | {
    booking: null;
}): Type {
    return "contact" in value ? Type.contact : "banquet" in value ? Type.banquet : "booking" in value ? Type.booking : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    contact: _ContactInquiry;
} | {
    banquet: _BanquetInquiry;
} | {
    booking: _BookingInquiry;
}): {
    __kind__: "contact";
    contact: ContactInquiry;
} | {
    __kind__: "banquet";
    banquet: BanquetInquiry;
} | {
    __kind__: "booking";
    booking: BookingInquiry;
} {
    return "contact" in value ? {
        __kind__: "contact",
        contact: value.contact
    } : "banquet" in value ? {
        __kind__: "banquet",
        banquet: value.banquet
    } : "booking" in value ? {
        __kind__: "booking",
        booking: value.booking
    } : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    upi: null;
} | {
    card: null;
} | {
    cash: null;
}): PaymentMode {
    return "upi" in value ? PaymentMode.upi : "card" in value ? PaymentMode.card : "cash" in value ? PaymentMode.cash : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    served: null;
} | {
    cooking: null;
} | {
    billed: null;
}): OrderStatus {
    return "pending" in value ? OrderStatus.pending : "served" in value ? OrderStatus.served : "cooking" in value ? OrderStatus.cooking : "billed" in value ? OrderStatus.billed : value;
}
function from_candid_variant_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    occupied: null;
} | {
    free: null;
} | {
    reserved: null;
}): TableStatus {
    return "occupied" in value ? TableStatus.occupied : "free" in value ? TableStatus.free : "reserved" in value ? TableStatus.reserved : value;
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GuestCheckIn>): Array<GuestCheckIn> {
    return value.map((x)=>from_candid_GuestCheckIn_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Inquiry>): Array<Inquiry> {
    return value.map((x)=>from_candid_Inquiry_n27(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BanquetBill>): Array<BanquetBill> {
    return value.map((x)=>from_candid_BanquetBill_n34(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RestaurantBill>): Array<RestaurantBill> {
    return value.map((x)=>from_candid_RestaurantBill_n40(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RestaurantExpense>): Array<RestaurantExpense> {
    return value.map((x)=>from_candid_RestaurantExpense_n50(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RestaurantOrder>): Array<RestaurantOrder> {
    return value.map((x)=>from_candid_RestaurantOrder_n58(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RestaurantReceipt>): Array<RestaurantReceipt> {
    return value.map((x)=>from_candid_RestaurantReceipt_n64(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RestaurantTable>): Array<RestaurantTable> {
    return value.map((x)=>from_candid_RestaurantTable_n68(_uploadFile, _downloadFile, x));
}
function to_candid_BanquetBill_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BanquetBill): _BanquetBill {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_GuestCheckInStatus_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GuestCheckInStatus): _GuestCheckInStatus {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_GuestCheckIn_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GuestCheckIn): _GuestCheckIn {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_OrderStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentMode_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMode): _PaymentMode {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_RestaurantBill_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RestaurantBill): _RestaurantBill {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_RestaurantExpense_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RestaurantExpense): _RestaurantExpense {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_RestaurantOrder_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RestaurantOrder): _RestaurantOrder {
    return to_candid_record_n16(_uploadFile, _downloadFile, value);
}
function to_candid_RestaurantReceipt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RestaurantReceipt): _RestaurantReceipt {
    return to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid_RestaurantTable_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RestaurantTable): _RestaurantTable {
    return to_candid_record_n74(_uploadFile, _downloadFile, value);
}
function to_candid_TableStatus_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TableStatus): _TableStatus {
    return to_candid_variant_n76(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    date: bigint;
    description: string;
    paymentMode: PaymentMode;
    category: string;
    amount: number;
}): {
    id: string;
    date: bigint;
    description: string;
    paymentMode: _PaymentMode;
    category: string;
    amount: number;
} {
    return {
        id: value.id,
        date: value.date,
        description: value.description,
        paymentMode: to_candid_PaymentMode_n5(_uploadFile, _downloadFile, value.paymentMode),
        category: value.category,
        amount: value.amount
    };
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: GuestCheckInStatus;
    createdAt: bigint;
    checkInDate: string;
    guestName: string;
    roomNumber: string;
    children: bigint;
    idNumber: string;
    totalAmount: number;
    notes: string;
    advancePaid: number;
    adults: bigint;
    expectedCheckOut: string;
    phone: string;
    idType: string;
    actualCheckOut: string;
}): {
    id: string;
    status: _GuestCheckInStatus;
    createdAt: bigint;
    checkInDate: string;
    guestName: string;
    roomNumber: string;
    children: bigint;
    idNumber: string;
    totalAmount: number;
    notes: string;
    advancePaid: number;
    adults: bigint;
    expectedCheckOut: string;
    phone: string;
    idType: string;
    actualCheckOut: string;
} {
    return {
        id: value.id,
        status: to_candid_GuestCheckInStatus_n13(_uploadFile, _downloadFile, value.status),
        createdAt: value.createdAt,
        checkInDate: value.checkInDate,
        guestName: value.guestName,
        roomNumber: value.roomNumber,
        children: value.children,
        idNumber: value.idNumber,
        totalAmount: value.totalAmount,
        notes: value.notes,
        advancePaid: value.advancePaid,
        adults: value.adults,
        expectedCheckOut: value.expectedCheckOut,
        phone: value.phone,
        idType: value.idType,
        actualCheckOut: value.actualCheckOut
    };
}
function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    customerName?: string;
    status: OrderStatus;
    createdAt: bigint;
    tableId: string;
    gstAmount: number;
    totalAmount: number;
    items: Array<OrderItem>;
}): {
    id: string;
    customerName: [] | [string];
    status: _OrderStatus;
    createdAt: bigint;
    tableId: string;
    gstAmount: number;
    totalAmount: number;
    items: Array<_OrderItem>;
} {
    return {
        id: value.id,
        customerName: value.customerName ? candid_some(value.customerName) : candid_none(),
        status: to_candid_OrderStatus_n17(_uploadFile, _downloadFile, value.status),
        createdAt: value.createdAt,
        tableId: value.tableId,
        gstAmount: value.gstAmount,
        totalAmount: value.totalAmount,
        items: value.items
    };
}
function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    source: string;
    date: bigint;
    note: string;
    paymentMode: PaymentMode;
    amount: number;
}): {
    id: string;
    source: string;
    date: bigint;
    note: string;
    paymentMode: _PaymentMode;
    amount: number;
} {
    return {
        id: value.id,
        source: value.source,
        date: value.date,
        note: value.note,
        paymentMode: to_candid_PaymentMode_n5(_uploadFile, _downloadFile, value.paymentMode),
        amount: value.amount
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    contactName: string;
    guestCount: bigint;
    createdAt: bigint;
    gstPercent: number;
    hallName: string;
    totalAmount: number;
    paymentMode: PaymentMode;
    extraCharges: number;
    perPlateRate: number;
    eventName: string;
    contactPhone: string;
}): {
    id: string;
    contactName: string;
    guestCount: bigint;
    createdAt: bigint;
    gstPercent: number;
    hallName: string;
    totalAmount: number;
    paymentMode: _PaymentMode;
    extraCharges: number;
    perPlateRate: number;
    eventName: string;
    contactPhone: string;
} {
    return {
        id: value.id,
        contactName: value.contactName,
        guestCount: value.guestCount,
        createdAt: value.createdAt,
        gstPercent: value.gstPercent,
        hallName: value.hallName,
        totalAmount: value.totalAmount,
        paymentMode: to_candid_PaymentMode_n5(_uploadFile, _downloadFile, value.paymentMode),
        extraCharges: value.extraCharges,
        perPlateRate: value.perPlateRate,
        eventName: value.eventName,
        contactPhone: value.contactPhone
    };
}
function to_candid_record_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: TableStatus;
    seats: bigint;
    currentOrderId?: string;
}): {
    id: string;
    status: _TableStatus;
    seats: bigint;
    currentOrderId: [] | [string];
} {
    return {
        id: value.id,
        status: to_candid_TableStatus_n75(_uploadFile, _downloadFile, value.status),
        seats: value.seats,
        currentOrderId: value.currentOrderId ? candid_some(value.currentOrderId) : candid_none()
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    customerName?: string;
    createdAt: bigint;
    tableId: string;
    gstAmount: number;
    orderId: string;
    totalAmount: number;
    discount: number;
    paymentMode: PaymentMode;
    items: Array<OrderItem>;
    subtotal: number;
}): {
    id: string;
    customerName: [] | [string];
    createdAt: bigint;
    tableId: string;
    gstAmount: number;
    orderId: string;
    totalAmount: number;
    discount: number;
    paymentMode: _PaymentMode;
    items: Array<_OrderItem>;
    subtotal: number;
} {
    return {
        id: value.id,
        customerName: value.customerName ? candid_some(value.customerName) : candid_none(),
        createdAt: value.createdAt,
        tableId: value.tableId,
        gstAmount: value.gstAmount,
        orderId: value.orderId,
        totalAmount: value.totalAmount,
        discount: value.discount,
        paymentMode: to_candid_PaymentMode_n5(_uploadFile, _downloadFile, value.paymentMode),
        items: value.items,
        subtotal: value.subtotal
    };
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GuestCheckInStatus): {
    checkedIn: null;
} | {
    checkedOut: null;
} {
    return value == GuestCheckInStatus.checkedIn ? {
        checkedIn: null
    } : value == GuestCheckInStatus.checkedOut ? {
        checkedOut: null
    } : value;
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    pending: null;
} | {
    served: null;
} | {
    cooking: null;
} | {
    billed: null;
} {
    return value == OrderStatus.pending ? {
        pending: null
    } : value == OrderStatus.served ? {
        served: null
    } : value == OrderStatus.cooking ? {
        cooking: null
    } : value == OrderStatus.billed ? {
        billed: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMode): {
    upi: null;
} | {
    card: null;
} | {
    cash: null;
} {
    return value == PaymentMode.upi ? {
        upi: null
    } : value == PaymentMode.card ? {
        card: null
    } : value == PaymentMode.cash ? {
        cash: null
    } : value;
}
function to_candid_variant_n76(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TableStatus): {
    occupied: null;
} | {
    free: null;
} | {
    reserved: null;
} {
    return value == TableStatus.occupied ? {
        occupied: null
    } : value == TableStatus.free ? {
        free: null
    } : value == TableStatus.reserved ? {
        reserved: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
